export const AllNodeTypes = `
    llm,
    imageGen,
    imageDisplay,
    imageTiles,
    sketchPad,
    textInput,
    textOutput,
    wordSelector,
    wordArranger,
    flipCard,
    chatInterface,
    triggerButton,
    audioPlayer,
    textToSpeech,
    audioRecorder,
    speechToText,
    camera,
    fileUpload,
`;

export const AllNodeNames = `
    LLMNode Node,
    ImageGen Node,
    ImagesDisplay Node,
    ImageTiles Node,
    SketchPad Node,
    TextInput Node,
    TextOutput Node,
    WordSelector Node,
    WordArranger Node,
    FlipCard Node,
    ChatInterface Node,
    CustomNode Node,    
    TriggerButton Node,
    AudioPlayer Node,
    TextToSpeech Node,
    AudioRecorder Node,
    SpeechToText Node,
    Camera Node,
    FileUpload Node,
`;

export const AllUIComponentTypes = `
    imageDisplay,
    imageTiles,
    sketchPad,
    textInput,
    textOutput,
    wordSelector,
    wordArranger,
    flipCard,
    chatInterface,
    triggerButton,
    audioPlayer,
    audioRecorder,
    camera,
    fileUpload,
`;
